export const PREMIUM_MIGRATION_COPY = {
  page: {
    eyebrow: "Premium / Chuyển đổi",
    title: "Chuyển đổi thuê bao",
    description:
      "Queue vận hành chuẩn cho chuyển đổi premium: lọc server-side, review chi tiết, chỉnh yêu cầu chờ xử lý và thực thi start/complete/fail/cancel ngay trên admin surface.",
    createButton: "Tạo yêu cầu chuyển đổi",
    loadCatalogsError: {
      subscriptions: (error: string) => `Không thể tải thuê bao: ${error}`,
      accounts: (error: string) => `Không thể tải kho premium: ${error}`,
      fallback: "Lỗi kết nối khi tải dữ liệu nguồn cho chuyển đổi",
    },
    loadMigrationsError: {
      api: (error: string) => `Không thể tải queue chuyển đổi: ${error}`,
      fallback: "Lỗi kết nối khi tải dữ liệu chuyển đổi",
    },
    loadDetailError: {
      api: (error: string) => `Không thể tải chi tiết chuyển đổi: ${error}`,
      fallback: "Lỗi kết nối khi tải chi tiết chuyển đổi",
    },
    filters: {
      subscription: "Thuê bao",
      sourceAccount: "Kho nguồn",
      targetAccount: "Kho đích",
      customerId: "Mã khách hàng",
      pageSize: "Số dòng / trang",
      fromDate: "Từ ngày",
      toDate: "Đến ngày",
      allSubscriptions: "Tất cả thuê bao",
      allSourceAccounts: "Tất cả kho nguồn",
      allTargetAccounts: "Tất cả kho đích",
      rowsPerPage: (limit: number) => `${limit} dòng`,
      reset: "Reset filters",
      apply: "Áp dụng",
    },
  },
  request: {
    title: "Tạo yêu cầu chuyển đổi",
    description:
      "Tạo yêu cầu chuyển đổi đúng gói dịch vụ, có kiểm tra sức chứa và chuẩn bị sẵn cho lịch sử vận hành.",
    conditionsTitle: "Điều kiện bắt buộc",
    conditionsDescription: "Kho nguồn và kho đích phải cùng gói dịch vụ, còn sức chứa và không trùng nhau.",
    mainSectionTitle: "Thông tin chính",
    mainSectionDescription:
      "Chọn đúng thuê bao nguồn và kho đích. Danh sách kho đích đã được lọc theo gói dịch vụ và số slot khả dụng.",
    sourceSubscriptionLabel: "Thuê bao nguồn",
    sourceSubscriptionPlaceholder: "Tìm thuê bao theo khách hàng / gói dịch vụ...",
    sourceSubscriptionEmpty: "Không có thuê bao phù hợp",
    sourceSummaryPrefix: "Kho nguồn:",
    sourceServicePrefix: "Gói dịch vụ:",
    daysRemainingSuffix: "ngày",
    targetAccountLabel: "Kho đích",
    targetAccountPlaceholder: {
      withSubscription: "Chọn kho cùng dịch vụ...",
      withoutSubscription: "Chọn thuê bao trước",
    },
    targetAccountEmpty: "Chưa có kho đích phù hợp",
    targetSummary: (slots: number, serviceName: string) => `Còn ${slots} slot khả dụng | ${serviceName}`,
    reasonLabel: "Lý do chuyển đổi",
    reasonPlaceholder: "Ví dụ: Kho nguồn sắp hết sức chứa, cần chuyển sang kho mới...",
    notesLabel: "Ghi chú nội bộ",
    notesPlaceholder: "Ghi chú nội bộ, ví dụ: giữ nguyên chu kỳ thanh toán...",
    quickCheckTitle: "Kiểm tra nhanh",
    quickCheckDescription:
      "Tóm tắt nhanh trước khi gửi yêu cầu để vận hành thấy rõ kho nguồn, kho đích và sức chứa.",
    quickCheckSource: "Kho nguồn",
    quickCheckTarget: "Kho đích",
    quickCheckCapacity: "Sức chứa kho đích",
    quickCheckCapacityValue: (slots: number) => `${slots} chỗ trống`,
    quickCheckEmptyValue: "Chưa có",
    submit: "Tạo yêu cầu",
    noSubscription: "Chưa chọn",
  },
  statusCards: {
    pending: {
      label: "Chờ xử lý",
      description: "Yêu cầu đã tạo nhưng chưa bắt đầu quá trình chuyển đổi.",
    },
    inProgress: {
      label: "Đang xử lý",
      description: "Chuyển đổi đang chuyển dữ liệu hoặc chờ xác nhận.",
    },
    completed: {
      label: "Hoàn tất",
      description: "Đã chuyển xong và thuê bao đã nằm ở kho đích.",
    },
    failed: {
      label: "Thất bại",
      description: "Có lỗi, bị huỷ hoặc kết thúc không thành công.",
    },
  },
  list: {
    title: "Danh sách yêu cầu chuyển đổi",
    subtitle: (activeAccountsCount: number, activeSubscriptionsCount: number) =>
      `${activeAccountsCount} kho đích khả dụng · ${activeSubscriptionsCount} thuê bao active`,
    totalSuffix: "yêu cầu",
    loading: "Đang tải yêu cầu chuyển đổi...",
    emptyTitle: "Chưa có yêu cầu chuyển đổi nào",
    emptyDescription: "Tạo yêu cầu đầu tiên để bắt đầu theo dõi lịch sử xử lý.",
    columns: {
      customerStatus: "Khách hàng / trạng thái",
      sourceTarget: "Kho nguồn → kho đích",
      reasonNotes: "Lý do / ghi chú",
      createdAt: "Tạo lúc",
      actions: "Thao tác",
    },
    mobileColumns: {
      customerStatus: "Khách hàng / trạng thái",
      sourceTarget: "Kho nguồn → kho đích",
      reasonNotes: "Lý do / ghi chú",
      createdAt: "Tạo lúc",
    },
    rowSourceLabel: "Kho nguồn",
    rowTargetLabel: "Kho đích",
    rowSlotsSuffix: "slot",
    rowSlotsRemainingSuffix: "slot",
    viewDetail: "Xem chi tiết",
    viewCustomer: "Xem khách hàng",
    openSource: "Mở kho nguồn",
    openTarget: "Mở kho đích",
    copyId: "Sao chép mã",
    copySubscription: "Sao chép mã đăng ký",
    copyCustomerId: "Sao chép mã khách hàng",
    copyIdSuccess: "Đã sao chép mã chuyển đổi",
    copySubscriptionSuccess: "Đã sao chép mã đăng ký",
    copyCustomerSuccess: "Đã sao chép mã khách hàng",
    pagePrevious: "Trang trước",
    pageNext: "Trang sau",
    totalLabel: (total: number) => `${total} yêu cầu`,
  },
  detail: {
    overview: {
      eyebrow: "Tổng quan",
      title: "Tóm tắt hồ sơ chuyển đổi",
      description: "Hồ sơ vận hành của lần chuyển thuê bao từ kho nguồn sang kho đích.",
      badge: "Hồ sơ chuyển đổi",
      customerName: "Khách hàng",
      customerId: "Mã khách hàng",
      subscriptionId: "Mã đăng ký",
      migrationId: "Mã chuyển đổi",
      copyMigrationId: "Đã sao chép mã chuyển đổi",
      copyCustomerId: "Đã sao chép mã khách hàng",
      copySubscriptionId: "Đã sao chép mã đăng ký",
      createdAt: "Tạo lúc",
    },
    summary: {
      totalSteps: "Tổng bước",
      status: "Trạng thái",
      started: "Bắt đầu",
      completed: "Hoàn tất",
      pendingNote: "Đang chờ khởi chạy",
      runningNote: "Đã vào quy trình chuyển đổi",
      completedNote: "Đã hoàn tất chuyển đổi",
      notCompletedNote: "Chưa hoàn tất chuyển đổi",
      noReason: "Chưa có lý do kết thúc",
      reasonPrefix: "Lý do kết thúc:",
    },
    sourceTarget: {
      eyebrow: "Kho nguồn / kho đích",
      title: "Kho nguồn và kho đích",
      description: "Thông tin hai đầu chuyển đổi được hiển thị theo cùng một cấu trúc để kiểm tra nhanh.",
      sourceLabel: "Kho nguồn",
      targetLabel: "Kho đích",
      detailUnavailable: "Chưa có thông tin chi tiết",
      capacity: "Sức chứa",
      remaining: "Còn trống",
      open: "Mở",
      capacityValue: (used: number, total: number) => `${used}/${total}`,
    },
    requestSection: {
      eyebrow: "Yêu cầu",
      title: "Dữ liệu yêu cầu chuyển đổi",
      description: "Chỉ khi chưa bắt đầu chuyển đổi mới có thể chỉnh kho đích, lý do và ghi chú.",
      lockedNote: "Yêu cầu đã khóa vì quá trình chuyển đổi không còn ở trạng thái chờ.",
      editableNote: "Có thể đổi kho đích trước khi bắt đầu chuyển đổi.",
      saveButton: "Lưu yêu cầu",
      targetLabel: "Kho đích dự kiến",
      reasonLabel: "Lý do chuyển đổi",
      notesLabel: "Ghi chú vận hành",
    },
    execution: {
      eyebrow: "Thực thi",
      title: "Điều khiển quá trình chuyển đổi",
      description: "Chọn người nhận hiện có, tạo người nhận mới hoặc kết thúc bằng thất bại / huỷ khi có thay đổi.",
      canMutate: "Có thể thực hiện",
      readOnly: "Chỉ xem",
      loadingTargetUsers: "Đang tải danh sách người nhận...",
      targetUsersAvailable: (count: number) => `${count} người nhận khả dụng`,
      selectedTargetLabel: "Kho đích đã chọn",
      requiresTargetUserLabel: "Cần người nhận",
      requiresTargetUserRequired: "Bắt buộc",
      requiresTargetUserOptional: "Không bắt buộc",
      existingTargetUserLabel: "Người nhận hiện có",
      noExistingTargetUser: "Không chọn người nhận có sẵn",
      createNewTargetUserLabel: "Hoặc tạo người nhận mới",
      createNewTargetUserPlaceholder: "nguoi-nhan@example.com",
      failureReasonLabel: "Lý do nếu thất bại",
      failureReasonPlaceholder: "Bắt buộc khi quá trình chuyển đổi không hoàn tất.",
      start: "Bắt đầu",
      complete: "Hoàn tất",
      fail: "Đánh dấu thất bại",
      cancel: "Huỷ",
      startToast: "Đã bắt đầu chuyển đổi",
      completeToast: "Đã hoàn tất chuyển đổi",
      failToast: "Đã kết thúc chuyển đổi với trạng thái thất bại",
      cancelToast: "Đã huỷ chuyển đổi theo yêu cầu quản trị viên",
      validationNeedTargetUser: "Cần chọn người nhận hiện có hoặc tạo người nhận mới trước khi hoàn tất.",
      validationNeedFailureReason: "Nhập lý do thất bại trước khi đánh dấu thất bại.",
    },
    timeline: {
      eyebrow: "Lịch sử",
      title: "Dòng thời gian các bước chuyển đổi",
      description: "Mỗi bước được hiển thị theo trạng thái xử lý và có thể mở dữ liệu chi tiết khi cần đối chiếu.",
      empty: "Chưa có bước ghi nhận nào.",
      viewPayload: "Xem dữ liệu chi tiết",
      stepPrefix: "Bước",
    },
    copy: {
      fallback: "Không thể sao chép vào clipboard",
    },
    error: {
      cannotUpdate: "Không thể cập nhật chuyển đổi",
      updateConnection: "Lỗi kết nối khi cập nhật chuyển đổi",
    },
    modalTitle: "Chi tiết chuyển đổi",
  },
} as const;
