import { vi } from "@/shared/messages/vi";

export const INVENTORY_COPY = {
  close: vi.common.close,
  page: vi.inventory.page,
  sourceAccountDetail: vi.inventory.sourceAccountDetail,
  addConnectionDialog: vi.inventory.addConnectionDialog,
  inventoryDetailDrawer: vi.inventory.page.detailDrawer,
  header: {
    title: "Quản lý kho hàng",
    description: "Nhấn chuột phải vào dòng để mở menu thao tác. Cập nhật dữ liệu nhanh hơn.",
    searchPlaceholder: "Tìm kiếm tài khoản...",
    createKey: "Thêm License Key",
    smartMatch: "Quét Gợi Ý",
    exportCsv: "Xuất CSV",
    createAccount: "Thêm tài khoản",
  },
  filters: {
    productLabel: "Sản phẩm:",
    allProducts: "Tất cả sản phẩm",
    providerLabel: "Nhà cung cấp:",
    allProviders: "Tất cả",
    statusLabel: "Trạng thái:",
    allStatus: "Tất cả trạng thái",
    active: "Hoạt động (còn chỗ)",
    full: "Đã đầy (hết chỗ)",
    expiring7d: "Sắp hết hạn (< 7 ngày)",
    expired: "Đã hết hạn",
    clear: "Xóa bộ lọc",
  },
  stats: {
    sourceAccounts: "Tài khoản Nguồn",
    licenseKeysAvailable: "License Key Có Sẵn",
    expiringSoon: "Sắp Hết Hạn",
    expired: "Đã Hết Hạn",
    nearFull: "Gần Đầy Slot",
    freeSlots: "Slot Còn Trống",
    totalPurchaseCost: "Tổng Chi Phí Mua",
    usedSlots: (used: number, total: number) => `${used}/${total} slots đã dùng`,
    totalAccounts: (count: number) => `${count} tổng tài khoản`,
    inDays: (days: number) => `${days} ngày tới`,
    within7Days: (count: number) => `(${count} trong 7 ngày!)`,
    below20Percent: "Dưới 20% slot trống",
    activeAccounts: (count: number) => `Trên ${count} tài khoản hoạt động`,
    totalInvestment: "VND tổng đầu tư",
  },
  overlays: {
    drawerTitle: (email?: string | null) => (email ? `Kho: ${email}` : "Kho dữ liệu"),
    connectionsTitle: "Quản lý Kết nối",
    activityTitle: "Lịch sử hoạt động",
    bulkDelete: {
      title: "Xác nhận xóa hàng loạt",
      heading: "Xác nhận xóa hàng loạt",
      description: "Hành động này không thể hoàn tác",
      body: (count: number) =>
        `Bạn có chắc muốn xóa ${count} tài khoản nguồn đã chọn? Tất cả kết nối và dữ liệu slot liên quan sẽ bị mất.`,
      cancel: "Hủy",
      confirm: (count: number) => `Xóa ${count} mục`,
    },
  },
  createSourceAccount: {
    modal: {
      title: "Thêm tài khoản nguồn",
      description: "Giữ layout nhập liệu rộng và gọn, tối ưu cho thao tác nhanh trên màn hình lớn lẫn mobile.",
      save: "Tạo tài khoản",
      cancel: "Hủy",
      success: "Tạo tài khoản nguồn thành công.",
      error: "Không thể tạo tài khoản nguồn.",
      required: "Email và nhà cung cấp là bắt buộc.",
    },
    identity: {
      title: "Thông tin tài khoản",
      description: "Giữ form gọn ở những trường nhập thật sự cần thiết để thao tác nhanh và ít nhầm hơn.",
      emailLabel: "Email đăng nhập *",
      emailPlaceholder: "admin@example.com",
      passwordLabel: "Mật khẩu",
      passwordEditLabel: "Mật khẩu mới (tùy chọn)",
      passwordHint: "Sẽ được mã hóa",
      passwordEditHint: "Bỏ trống nếu không đổi",
      providerLabel: "Nguồn cung cấp (Provider) *",
    },
    allocation: {
      title: "Cấu hình cấp phát",
      description: "Giữ các trường về sản phẩm, slot và hạn dùng trong cùng một vùng để đọc và rà nhanh hơn.",
      productLabel: "Sản phẩm khả dụng *",
      capacityLabel: "Sức chứa (tổng slots) *",
      expiryLabel: "Ngày hết hạn *",
    },
    credentials: {
      title: "Dữ liệu đăng nhập",
      description: "Danh sách credential được giữ riêng để dễ tái sử dụng và giảm lỗi khi cần đối soát.",
    },
    cost: {
      title: "Giá mua (VND)",
      date: "Ngày mua",
      source: "Nguồn mua",
      sourcePlaceholder: "VD: Shopee, Tiki, nhà cung cấp A",
    },
    advancedOptions: "Tùy chọn nâng cao",
  },
  editSourceAccount: {
    modal: {
      title: "Sửa thông tin tài khoản nguồn",
      description: "Nhập nhanh phần cần đổi, còn các phần nâng cao được giữ gọn ở dưới để giảm rối mắt.",
      save: "Lưu thay đổi",
      cancel: "Hủy",
      success: "Cập nhật tài khoản nguồn thành công.",
      error: "Không thể cập nhật tài khoản nguồn.",
      required: "Email và nhà cung cấp là bắt buộc.",
    },
  },
  createLicenseKey: {
    modal: {
      title: "Thêm License Key mới",
      description: "Nhập mã key và gắn vào sản phẩm tương ứng. Các trường còn lại sẽ được hệ thống khởi tạo tự động.",
      save: "Tạo key",
      cancel: "Hủy",
      success: "Tạo License Key thành công.",
      error: "Không thể tạo License Key.",
      keyRequired: "Vui lòng nhập mã License Key.",
      productRequired: "Vui lòng chọn sản phẩm.",
    },
    main: {
      title: "Thông tin chính",
      description: "Giữ form gọn để nhập nhanh, tránh làm người dùng phải đi qua nhiều lớp cấu hình không cần thiết.",
      keyLabel: "Mã License Key",
      productLabel: "Sản phẩm",
      productPlaceholder: "Chọn sản phẩm",
    },
    delete: {
      title: "Xác nhận xóa License Key",
      description: "Thao tác này sẽ đưa key vào thùng rác. Bạn vẫn có thể khôi phục lại từ màn chi tiết hoặc trang thùng rác.",
      save: "Đưa vào thùng rác",
      cancel: "Hủy",
      question: "Bạn chắc chắn muốn xóa?",
      body: (keyCode?: string | null) => `License Key “${keyCode ?? "—"}” sẽ bị đưa vào thùng rác.`,
      success: "Đã xóa License Key.",
      error: "Không thể xóa License Key.",
    },
  },
  sourceAccountImport: {
    templateTitle: "Tải file mẫu CSV",
    templateButton: "Mẫu",
    importButton: "Import Excel",
    importing: "Đang nhập...",
    popupTitle: "Kết quả Import",
    totalRows: (count: number) => `Tổng: ${count} dòng trong file`,
    totalRowsLabel: "dòng trong file",
    created: (count: number) => `${count} tạo thành công`,
    createdSuffix: "tạo thành công",
    skipped: (count: number) => `${count} bỏ qua (lỗi validate)`,
    skippedSuffix: "bỏ qua (lỗi validate)",
    dbErrors: (count: number) => `${count} lỗi database`,
    dbErrorsSuffix: "lỗi database",
    errorDetails: "Chi tiết lỗi",
    errorRow: (row: number, message: string) => `Dòng ${row}: ${message}`,
    excelOnlyError: "Chỉ chấp nhận file Excel (.xlsx, .xls)",
    tooLargeError: "File quá lớn. Tối đa 5MB",
    success: (count: number) => `Đã nhập ${count} tài khoản thành công!`,
    uploadError: "Lỗi kết nối khi upload file",
    loadError: (message: string) => `Lỗi import: ${message}`,
  },
  smartMatch: {
    title: "Quét Gợi Ý Kết Nối Thông Minh",
    description: "So khớp nick / ghi chú đơn hàng với email / ghi chú kho hàng",
    emptyTitle: "Chưa có kết quả",
    emptyDescription:
      "Nhấn nút bên dưới để hệ thống quét và so khớp tự động các đơn hàng chưa kết nối với kho hàng phù hợp.",
    emptyResultTitle: "Không tìm thấy gợi ý nào",
    emptyResultDescription:
      "Tất cả đơn hàng đã được kết nối hoặc không có nick/ghi chú khớp với kho.",
    scan: "Quét ngay",
    rescans: "Quét lại",
    scanning: "Đang quét...",
    connect: "Kết nối",
    dismiss: "Bỏ qua",
    selectAll: "Chọn tất cả",
    deselectAll: "Bỏ chọn tất cả",
    connectSelected: (count: number) => `Kết nối ${count} mục`,
    connected: (customer: string, sourceEmail: string) => `Đã kết nối ${customer} ↔ ${sourceEmail}`,
    scanError: "Quét thất bại",
    connectError: "Kết nối thất bại",
    connectedSuccess: (count: number) => `Đã kết nối thành công ${count} gợi ý`,
    connectedFail: (count: number) => `${count} gợi ý kết nối thất bại`,
    matchLabels: {
      nickUsed: "Nick đã dùng",
      itemNotes: "Ghi chú đơn",
      registry: "Danh bạ nick",
      reservedNick: "Nick đã giữ",
    },
    confidence: {
      high: "Cao",
      medium: "Trung bình",
      low: "Thấp",
    },
  },
  inventoryTable: {
    title: "Tài khoản nguồn (Pool)",
    description: "Quản lý tài khoản nguồn, slot và hạn dùng trong một màn hình.",
    selectAll: "Chọn tất cả",
    providerLabel: "Nhà CC",
    productLabel: "Sản phẩm",
    slotsLabel: "SLOTS",
    accountField: "Tài khoản",
    providerField: "Nhà cung cấp",
    productField: "Sản phẩm",
    slotField: "Slot",
    expiryField: "Hết hạn",
    statusField: "Trạng thái",
    fullLabel: "Đã đầy",
    emptyValue: "N/A",
    noData: "Không có tài khoản nguồn nào",
    noDataDescription: "Chưa có dữ liệu tài khoản.",
    outOfSlots: "Đã đầy",
    expired: "Hết hạn",
    active: "Hoạt động",
    fullCompact: "Đầy",
    daysLeft: (days: number) => `Còn ${days} ngày`,
    paginationInfo: (from: number, to: number, total: number) => `Hiển thị ${from}-${to} / ${total} tài khoản`,
    prevPage: "Trước",
    nextPage: "Tiếp",
    countSuffix: "tài khoản",
    showingPrefix: "Hiển thị",
  },
  comboboxes: {
    noContact: "Chưa có liên hệ",
    providerPlaceholder: "Tìm nhà cung cấp...",
    createProvider: "Thêm nhà cung cấp mới",
    productPlaceholder: "Tìm sản phẩm...",
    createProduct: "Tạo sản phẩm mới",
    noProduct: "Không tìm thấy sản phẩm phù hợp",
  },
  capacityAlert: {
    lowCapacityTitle: (count: number) => `${count} tài khoản sắp đầy slot`,
    lowCapacityDescription: "Các tài khoản nguồn dưới 20% slot trống. Cần bổ sung hoặc nâng cấp.",
    lowCapacityItem: (freeSlots: number, maxSlots: number, freePercent: number) =>
      `${freeSlots}/${maxSlots} slot trống (${freePercent}%)`,
    expiringTitle: (count: number) => `${count} tài khoản hết hạn trong 7 ngày`,
    expiringDescription: "Cần gia hạn hoặc di chuyển dữ liệu trước khi hết hạn.",
    expiringItem: (daysLeft: number) => `${daysLeft} ngày còn lại`,
  },
  addConnectionDialogUi: {
    quantityShort: (quantity: number) => `SL: ${quantity}`,
    separator: "•",
  },
  sourceAccountDetailFallbacks: {
    slotAnalysis: "phân tích slot",
    connections: "kết nối",
    connectionDetail: "chi tiết kết nối",
    duolingoFamily: "Gia đình Duolingo",
    activityLog: "lịch sử hoạt động",
  },
  sourceAccountConnections: {
    loadError: "Không thể tải chi tiết kết nối.",
    empty: "Chưa có kết nối nào cho tài khoản nguồn này.",
  },
  sourceAccountTrash: {
    banner: "Tài khoản nguồn này đang ở thùng rác. Bạn có thể khôi phục hoặc xóa vĩnh viễn ngay trên màn chi tiết này.",
    restore: "Khôi phục",
    purge: "Xóa vĩnh viễn",
  },
  licenseKeyDetail: {
    title: "Chi tiết License Key",
    description:
      "Xem thông tin license key và thực hiện khôi phục hoặc xóa vĩnh viễn khi key đang ở thùng rác.",
    notFoundTitle: "Không tìm thấy license key",
    notFoundDescription:
      "Key có thể đã bị xóa hoàn toàn hoặc không còn thuộc về tài khoản hiện tại.",
    trashBanner:
      "License key này đang nằm trong thùng rác. Bạn có thể khôi phục hoặc xóa vĩnh viễn ngay tại đây.",
    productPrefix: "Sản phẩm:",
    rowLabels: {
      keyCode: "Mã key",
      status: "Trạng thái",
      product: "Sản phẩm",
      id: "ID",
      createdAt: "Ngày tạo",
      updatedAt: "Cập nhật",
      orderId: "Gán vào đơn",
      assignedAt: "Gán lúc",
      deletedAt: "Xóa lúc",
    },
    statusBadge: {
      trash: "Đang ở thùng rác",
    },
    trashNote:
      "Khôi phục key sẽ đưa nó trở lại kho. Xóa vĩnh viễn sẽ gỡ key khỏi hệ thống.",
    close: "Đóng",
    restore: "Khôi phục",
    purge: "Xóa vĩnh viễn",
  },
  duolingoFamily: {
    errors: {
      decryptFailed: "Không thể giải mã mật khẩu",
      missingCredentials: "Thiếu email hoặc mật khẩu",
      loginFailed: "Đăng nhập Duolingo thất bại",
      loadFailed: "Lỗi khi tải dữ liệu Family",
    },
    toasts: {
      membersLoaded: (count: number) => `Đã tải ${count} thành viên Family.`,
      noMembersFound: "Family Plan nhưng API chưa trả về danh sách thành viên.",
      notFamilyPlan: "Tài khoản này không phải Family Plan.",
      copiedList: "Đã sao chép danh sách thành viên.",
      copiedInviteToken: "Đã sao chép Invite Token.",
    },
    empty: {
      title: "Duolingo Family Plan",
      description: "Đồng bộ để xem thành viên trong Family Plan.",
      sync: "Đồng bộ từ Duolingo",
      syncing: "Đang đồng bộ...",
    },
    nonFamily: {
      title: "Không phải Family Plan",
      packageLabel: "Tài khoản này đang dùng gói:",
      fallbackPlan: "Individual",
      refresh: "Kiểm tra lại",
    },
    header: {
      familyPlan: "Family Plan",
      sync: "Đồng bộ",
      joined: "Đã join",
      freeSlots: "Còn trống",
    },
    inviteToken: {
      label: "Invite Token",
      copyTitle: "Sao chép Invite Token",
    },
    members: {
      title: "Thành viên",
      copiedAll: "Đã sao chép!",
      copyAll: "Sao chép tất cả",
      owner: "Owner",
      fallbackUser: (id: number) => `User #${id}`,
      idLabel: "ID",
      empty: "Không tìm thấy thành viên nào.",
      copyTitle: (value: string | number) => `Sao chép ${value}`,
      profileTitle: (username: string) => `Xem hồ sơ ${username}`,
    },
  },
  dynamicCredentials: {
    types: {
      linkJoin: { label: "Link tham gia", placeholder: "https://..." },
      twoFa: { label: "Mã 2FA", placeholder: "Mã 2FA hoặc secret key..." },
      twoFaBackup: { label: "Mã dự phòng 2FA", placeholder: "Mã backup 2FA..." },
      duolingoId: { label: "Duolingo ID", placeholder: "Tự lấy hoặc nhập tay..." },
      other: { label: "Khác", placeholder: "Giá trị..." },
    },
    errors: {
      missingBaseCredentials: "Vui lòng nhập email hoặc username và mật khẩu đăng nhập kho ở trên trước.",
      loginFailed: "Đăng nhập Duolingo thất bại.",
      loginConnectionFailed: "Lỗi kết nối khi đăng nhập Duolingo.",
      missingUsername: "Nhập username hoặc @username vào ô để lấy ID.",
      lookupFailed: (username: string) => `Không tìm thấy ID cho "${username}".`,
      lookupConnectionFailed: "Lỗi kết nối khi lấy Duolingo ID.",
    },
    toasts: {
      copiedInviteToken: "Đã sao chép Invite Token.",
      lookupSuccess: (username: string, id: number) => `Lấy ID thành công: ${username} / ${id}.`,
      loginSuccess: (parts: string[]) => parts.join(" • "),
    },
    header: {
      title: "Thông tin đăng nhập kho",
      description: "Link join, 2FA và các khóa truy cập khác.",
      addDuolingoId: "Thêm Duolingo ID",
      addField: "Thêm trường",
    },
    duolingoLogin: {
      idle: "Đăng nhập Duolingo để lấy ID, username và Family",
      loading: "Đang đăng nhập Duolingo...",
      profile: "Trang cá nhân",
      plus: "Plus",
      idLabel: "ID",
      xpLabel: "XP",
      familyPlan: "Family Plan",
      joined: "Đã join",
      freeSlots: "Còn trống",
      inviteToken: "Invite Token",
      inviteTokenTitle: "Sao chép Invite Token",
      members: "Thành viên",
      owner: "Owner",
      packageLabel: "Gói",
      activeLabel: "Đang hoạt động",
      copyTitle: (value: string | number) => `Sao chép ${value}`,
    },
    empty: "Chưa có thông tin đăng nhập. Nhấn + để thêm.",
    otherLabelPlaceholder: "Tên trường...",
    duolingoInputPlaceholder: "Nhập username để lấy ID hoặc nhập ID tay...",
    fetchDuolingoId: "Lấy ID",
  },
} as const;
